title: Rob Kravec
logo: "/images/Headshot.JPG?raw=true" 
description: > 
  M.S. Student in Statistics at Duke University, Class of 2022 
  <br>
  Worked at McKinsey & Company and Capital One for three years following
  <br>
  Chemical Engineering B.S. from Stanford University
  <br><br>
  <a href="https://www.linkedin.com/in/robert-kravec-49873a89/">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/robert-kravec-49873a89/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 255724051 
