title: Rob Kravec
logo: "/images/Headshot.JPG?raw=true" 
description: > 
  M.S. Student in Statistics at Duke University, Class of 2022 
  <br><br>
  3 years of full-time work experience with McKinsey and Capital One
  <br><br>
  B.S. in Chemical Engineering from Stanford University
  <br><br>
  <a href="https://github.com/robkravec/robkravec.github.io/tree/master/images/Resume.pdf">View My Resume</a type = "application/pdf">
  <br><br>
  <a href="https://www.linkedin.com/in/robert-kravec-49873a89/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 255724051 
